spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.xiyczdveosfomdctmsix
spring.datasource.password=Rp74185t23#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
cors.origenes.permitidos=https://automapro-frontend.vercel.app,http://localhost:4200
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
ruta.almacenamiento.archivos=./archivos-aplicaciones
logging.level.com.automapro=INFO
logging.level.org.springframework.security=WARN
lemonsqueezy.api.key=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NGQ1OWNlZi1kYmI4LTRlYTUtYjE3OC1kMjU0MGZjZDY5MTkiLCJqdGkiOiJlMmVmOTI0MjJlMGM2YThiZmZkYTM3MWJhYTljZmRkODcwMTQzYTljMDkzN2JjNzIxYTgwZjBmMmY0OWI2OWE3NDIzNDRhZjc0ZDJjZjNjZiIsImlhdCI6MTc3MzcyODAwMC41NjM2MTUsIm5iZiI6MTc3MzcyODAwMC41NjM2MTcsImV4cCI6MTc4OTYwMzIwMC4wMzkyMjUsInN1YiI6IjY3MTg3NTEiLCJzY29wZXMiOltdfQ.gzejm8G_cTNrlnGgKgRDo0syyyB3Qg7cQVwVHpQpgdYLZUSDyXAVSTVoYfgEZH3JhDoPNWi33yFjiuyxOl5qtWC1lVyRFxBLzaIfX47T-0L6jOfvMELDbzgU_wQqYEX_49QEYg03o6Rv_Z9mMhcQluEGLeV0Ch5HC92pDE2pJUD8mPkA6vr0Wf3LKPyj8ZjvxMocJSOcJnqGwXsK7tCK5CO7b34bbGaoR3YRIqzfPPRzhqJB6whTIgik2MkXLrgYyxLcSWHjFOYZkO1MMnr5-VNEn3GWpTkwkiDHPLHyvtlgsiMDm7C4UmeTUWIMoI8pW6ggRADvz7kacSTpJt_RtQ9i6lDloikPbq4VXOeqD0cTnP-VZKEGR0AvF-TAPHktsRFn_Uqm9CLGwtNtlXWJ_kDXEaDPeIFuFAA6qxF7GOAZVSkrW-74eUT6uKchGzCg8xS7T25OGcAfJcw46hxqflSzx8tMK8ijaoummXM0ddmvffnjaPl6jjSd4JYyqJ2-EOL_38OfY2sO4468BirM1q5Q0qbAw36XX-2qFsBrqa7gGUlLl6qdkNiblRl-245YZrk-gIAFky61oNi8yjViwXkcDQ2ctF4YtUtmZx1YciztmtNrSvBWgI6G0ngFpKVbo16nKLjw125JQo6nMNydqqMaFGGbSYN3-YZnM0ZHtJw
lemonsqueezy.webhook.secret=automapro_webhook_2025
lemonsqueezy.variant.id=1412790
lemonsqueezy.store.id=318289
jwt.secret=AutomaProSuperSecretKeyParaJWT2024DebeSerLargaYSegura
jwt.expiracion=86400000
supabase.url=${SUPABASE_URL}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
supabase.storage.bucket=${SUPABASE_STORAGE_BUCKET}
resend.api.key=${RESEND_API_KEY}