spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.xiyczdveosfomdctmsix
spring.datasource.password=Rp74185t23#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
cors.origenes.permitidos=https://automapro-frontend.vercel.app,http://localhost:4200
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
ruta.almacenamiento.archivos=./archivos-aplicaciones
logging.level.com.automapro=INFO
logging.level.org.springframework.security=WARN